---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - php
  fixme:
    enabled: true
    strings:
    - BUG
    - CUSTOM
    - FIXME
    - HACK
    - TODO
  phpmd:
    enabled: true
    config:
      file_extensions: "php"
      rulesets: "phpmd.xml"
ratings:
  paths:
  - "**.php"
exclude_paths:
- setup/**/*
- tests/**/*
- vendor/**/*
